
remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: Gustavo A. Fernandez
  tagline: RF Engineer. Data Scientist
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    #- home
    - page
    - post
    
  social_links:
    twitter: gustavoflembert
    github: gustavofernandezlembert
    linkedIn: in/gustavofernandezlembert
    
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache
  - jekyll-seo-tag



