


remote_theme           : mmistakes/minimal-mistakes
minimal_mistakes_skin    : contrast

# Site Settings
locale                   : en-US
title                    : Site Title
title_separator          : -
subtitle                 : site tagline that appears below site title in masthead
name                     : Your Name
description              : An amazing website.
url                      : https://gustavofernandezlembert.github.io/Gustavo-Fernandez/


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache



