remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "contrast"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

layout: single
sidebar:
  - title: "Title"
    image: /path-to-image/
    image_alt: "image description"
    text: "Some text here."







