


remote_theme           : mmistakes/minimal-mistakes
minimal_mistakes_skin    : contrast


plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache



