
remote_theme: samarsault/plainwhite-jekyll


plainwhite:
  name: Gustavo A. Fernandez
  tagline: RF Engineer. Data Scientist
  date_format: "%b %-d, %Y"

  social_links:
    twitter: gustavoflembert
    github: gustavofernandezlembert
    linkedIn: in/gustavofernandezlembert





plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache



